lagou:
  message: logaou800
mysql:
  url: http://localhost?3306


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    
  #邮件
  mail:
    host: smtp.163.com #发送邮件服务器
    username: zhixiangshan@163.com #发送邮件的邮箱地址
    password: WDZIIUGJRFZFBLNB #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: zhixiangshan@163.com # 发送邮件的地址，和上面username一致
    protocol:smtp
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  

refreshTime:10
refreshCount:100

